<h1>Import Variable</h1>
<div class="alert alert-info">
<small>
	<b>Please use the following format:</b><br/>
	ee;name;value[;type]<br />
	es;name;value;stepgroupLabel[;type]<br />
	esl;name;value;stepgroupLabel;stepgroupLoop[;type]<br />
	ge;name;value;groupLabel[;type]<br />
	gs;name;value;groupLabel;stepgroupLabel[;type]<br />
	gsl;name;value;groupLabel;stepgroupLabel;stepgroupLoop[;type]<br />
	pe;name;value;participantLabel[;type]<br />
	ps;name;value;participantLabel;stepgroupLabel[;type]<br />
	psl;name;value;participantLabel;stepgroupLabel;stepgroupLoop[;type]<br />
</small>
</div>

<div class="alert alert-warning">Existing variables with the same name and context will be overwritten!</div>

<?php
echo $this->form;