<div id="cheader">
	<div id="cheadtexts">
		<span id="cheadline">The experiment is paused</span><br />
		<span id="cheadtext">Please wait until the experimenter resumes the experiment.</span>
	</div>
</div>
<?php
$this->headScript()->captureStart();
?>
function ReloadSync () {
	var href = location.href;
	location.href = href;
}
window.setTimeout("ReloadSync()", 2000);
<?php
$this->headScript()->captureEnd();
?>