<div style="margin: 20px 5px 20px 5px; padding: 10px; border: 2px solid #93c27a; background-color:#e5ffd7;">
<h1>
	<a href="/expadmin" style="text-decoration:none;font-weight:bold">
		<img src="/_media/Icons/book.png" alt="Administration" title="Administration" style="vertical-align: middle" />
		Session Administration
	</a>
</h1>
<p style="margin: 10px 0 20px 0">
	Manage and run your lab session.
</p>
<div class="actionToolbar">
	<ul>
		<li><a href="/expadmin"><img src="/_media/Icons/book.png" alt="Administration" title="Administration" /> Show existing Sessions</a></li>
		<li><a href="<?php echo $this->url(array('module'=>'expadmin', 'controller'=>'session', 'action'=>'add'), 'default', true); ?>"><img src="/_media/Icons/book_add.png" border="0" alt="" title=""> Create new Experiment Session</a></li>
	</ul>
	<div class="clear"></div>
</div>
</div>