<?php
$module = 'expdesigner';
$this->headLink()->appendStylesheet($this->sfwModuleAssetUrl('module.css', $module));
$this->inlineScript()->appendFile($this->sfwModuleAssetUrl('module.js', $module));

$this->headTitle('Edit Stepgroup', 'PREPEND');
$this->headTitle($this->stepgroup['name'], 'PREPEND');

$this->form->setLegend('Stepgroup - ' . $this->stepgroup['label']. ' :: ' . $this->stepgroup['name']);

echo $this->form;