<?php
$module = 'expdesigner';
$this->headLink()->appendStylesheet($this->sfwModuleAssetUrl('module.css', $module));
$this->inlineScript()->appendFile($this->sfwModuleAssetUrl('module.js', $module));

$this->headTitle('Edit Step ' . $this->steptype->adminGetSteptypeInfoName(), 'PREPEND');
$this->headTitle($this->step['name'], 'PREPEND');

$this->jsOnLoad()->appendScript('expdesigner.initStepTabContainer();');
?>
<div class="pull-right headingWithNavigation">
	<ul class="toolbar">
		<li><a href="<?php echo $this->url(array (
				'module' => $module,
				'controller' => 'step',
				'action' => 'previewnavigation',
				'stepId' => $this->step['id']
			), 'default', true); ?>"><img src="/_media/Icons/eye.png" alt="Preview step" title="Preview step" /> Preview Step</a></li>
		</ul>
</div>

<?php
echo $this->steptype->adminRender();