<?php
$module = 'expdesigner';
$this->headLink()->appendStylesheet($this->sfwModuleAssetUrl('module.css', $module));
$this->inlineScript()->appendFile($this->sfwModuleAssetUrl('module.js', $module));

$this->headTitle('Step Preview', 'PREPEND');
$this->headTitle($this->step['name'], 'PREPEND');
?>
<div class="headingWithNavigation">
	<ul class="toolbar">
		<li><a href="javascript:dojo.byId('previewFrame').contentWindow.location.reload()"><img src="/_media/Icons/arrow_refresh.png" alt="Refresh" title="Refresh" /> Refresh</a></li>
		<li><a href="<?php echo $this->url(array (
				'module' => 'expdesigner',
				'controller' => 'step',
				'action' => 'edit',
				'stepId' => $this->step['id']
			), 'default', true); ?>"><img src="/_media/Icons/page_edit.png" alt="Edit step" title="Edit step" /> Edit Step</a></li>
		</ul>
	<h1>Step Preview &ndash; <?php echo $this->escape($this->step['name']); ?></h1>
</div>

<div class="alert alert-info">
In some cases the preview function may not show a step correctly. If a step is obviously previewed inaccurately, please run a test session to check whether the problem still occurs.
</div>

<div class="center">
	<iframe style="width:100%;height:600px;" src="<?php echo $this->url(array('action'=>'preview')); ?>" id="previewFrame">Loading ...</iframe>
	<div>
		<div style="float: left;">
			<form action="<?php echo $this->url(array('jumpToStep'=>'previous')); ?>" method="GET">
				<input type="submit" value="Previous Step">
			</form>
		</div>
		<div style="float: right;">
			<form action="<?php echo $this->url(array('jumpToStep'=>'next')); ?>" method="GET">
				<input type="submit" value="Next Step">
			</form>
		</div>
		<form name="previewnavigationSelectForm" action="<?php echo $this->url(); ?>" method="GET">
			Jump to Step:
			<?php echo $this->formSelect('jumpToStep', $this->step['id'], array('onChange'=>'document.previewnavigationSelectForm.submit();'), $this->treatmentStructure); ?>
		</form>
	</div>
</div>

