<table class="table" id="sessionmonitor">
<thead>
<tr>
	<th>Stepgroup.Loop</th>
	<th>Step</th>
	<th>Participants</th>
	<th title="Options">O.</th>
</tr>
</thead>
<tbody id="smloop___new" class="hidden">
	<tr>
		<th colspan="2"><img src="/_media/Icons/door_open.png" /> Not yet logged in</th>
		<td class="participants" id="smparticipants___new"></td>
		<td></td>
	</tr>
</tbody>
<tbody id="smloop___wait_for_start" class="hidden">
	<tr>
		<th colspan="2"><img src="/_media/Icons/hourglass.png" /> Waiting for start</th>
		<td class="participants" id="smparticipants___wait_for_start"></td>
		<td></td>
	</tr>
</tbody>

<tbody id="smloop___finished" class="hidden">
	<tr>
		<th colspan="2"><img src="/_media/Icons/door.png" /> Finished!</th>
		<td class="participants" id="smparticipants___finished"></td>
		<td></td>
	</tr>
</tbody>
<tbody id="smloop___undefined" class="hidden">
	<tr>
		<th colspan="2"><img src="/_media/Icons/exclamation.png" /> Undefined</th>
		<td class="participants" id="smparticipants___undefined"></td>
		<td></td>
	</tr>
</tbody>
<tbody id="smloop___excluded" class="hidden">
	<tr>
		<th colspan="2">Excluded</th>
		<td class="participants" id="smparticipants___excluded"></td>
		<td></td>
	</tr>
</tbody>
</table>