<?php
$entriesFrom = $this->offset + 1;
$entriesTo = $entriesFrom + $this->limit - 1;
$maxPages = ceil($this->count / $this->limit);
if ($entriesTo > $this->count)
{
	$entriesTo = $this->count;
}
?>
<h2>Session Log</h2>

<div class="actionToolbar">
	<ul>
		<li><a href="javascript:expadmin.sessionLogLoadPage('<?php echo $this->url(array('module'=>'expadmin', 'controller' => 'log', 'action' => 'index', 'sessionId' => $this->session['id']), 'default', true); ?>', <?php echo $this->page; ?>);"><img src="/_media/Icons/arrow_refresh.png" border="0" alt="Refresh Log"> Refresh Log</a></li>
<?php if ($this->count > 0): ?>
		<li><a href="javascript:expadmin.sessionClearLog();"><img src="/_media/Icons/bin_empty.png" border="0" alt="Clear Log"> Clear Log</a></li>
<?php endif; ?>
<?php if ($maxPages > 1): ?>
		<li>
			<div class="btn-group" style="margin-bottom: 10px;">
				<button class="btn btn-default btn-ms" <?php if ($this->page <= 1) echo ' disabled="disabled"'; ?> onClick="expadmin.sessionLogLoadPage('<?php echo $this->url(array('module'=>'expadmin', 'controller' => 'log', 'action' => 'index', 'sessionId' => $this->session['id']), 'default', true); ?>', 1);">first page</button>
				<button class="btn btn-default btn-ms" <?php if ($this->page <= 1) echo ' disabled="disabled"'; ?> onClick="expadmin.sessionLogLoadPage('<?php echo $this->url(array('module'=>'expadmin', 'controller' => 'log', 'action' => 'index', 'sessionId' => $this->session['id']), 'default', true); ?>', <?php echo $this->page - 1; ?>);">previous page</button>
				<button class="btn btn-default btn-ms" <?php if ($this->page >= $maxPages) echo ' disabled="disabled"'; ?> onClick="expadmin.sessionLogLoadPage('<?php echo $this->url(array('module'=>'expadmin', 'controller' => 'log', 'action' => 'index', 'sessionId' => $this->session['id']), 'default', true); ?>', <?php echo $this->page + 1; ?>);">next page</button>
				<button class="btn btn-default btn-ms" <?php if ($this->page >= $maxPages) echo ' disabled="disabled"'; ?> onClick="expadmin.sessionLogLoadPage('<?php echo $this->url(array('module'=>'expadmin', 'controller' => 'log', 'action' => 'index', 'sessionId' => $this->session['id']), 'default', true); ?>', <?php echo $maxPages; ?>);">last page</button>
			</div>
		</li>
<?php endif; ?>
	</ul>
</div>

<?php
if ($this->count == 0)
{
	echo '<div>No log entries found.</div>';
	return;
}
?>

<form id="sessionLogFilterType" class="form-inline" role="form">
	Message Types:
<?php
	echo $this->formMultiCheckbox(
		'filterTypes', 
		$this->filterTypes, 
		array(
			'class' => 'checkbox',
			'escape' => false, 
			'onchange' => 'expadmin.sessionLogLoadPage(\'' . $this->url(array('module'=>'expadmin', 'controller' => 'log', 'action' => 'index', 'sessionId' => $this->session['id']), 'default', true) . '\', ' . $this->page . ');'
		), 
		array(
			'error' =>'Error', 
			'warning' => 'Warning', 
			'notice' => 'Notice', 
			'debug' => 'Debug',
			'event' => 'Event',
		), 
		' '
	);
?>
</form>

<div class="table-responsive">
<ul class="log" style="width:100%">
<?php
$i = $entriesFrom;

foreach ($this->logs as $log)
{
	echo '<li class="' . $log['type'] . '">';
		
		echo '<pre>';
		echo date('Y-m-d H:i:s', ceil($log['microtime']));
		echo ' ';
		echo $this->escape($log['content']);
		echo '</pre>';
		
		$hasContext = (!is_null($log['stepLabel']) || !is_null($log['stepgroupLabel']) || !is_null($log['stepgroupLoop']) || !is_null($log['participantLabel']) || !is_null($log['groupLabel']) );
		$hasDetails = (isset($log['details']) && $log['details'] != '');
		$hasData = (isset($log['data']) && $log['data'] != '');
		
		if ($hasContext || $hasDetails || $hasData)
		{
			echo '<div class="details">';
				echo '<a href="javascript:dojo.toggleClass(\'sessionLogDetails' . $log['id'] . '\', \'hidden\')">Details</a>';
				echo '<div id="sessionLogDetails' . $log['id'] . '" class="hidden">';
				if ($hasContext)
				{
					echo '<table class="table table-striped table-hover">';
					echo '<tr>';
						echo '<th>Group</th>';
						echo '<th>Participant</th>';
						echo '<th>Stepgroup Label</th>';
						echo '<th>Loop</th>';
						echo '<th>Step Label</th>';
					echo '</tr>';
						echo '<td>';
							echo (is_null($log['groupLabel'])) ? '&ndash;' : $log['groupLabel'];
						echo '</td>';
						echo '<td>';
							echo (is_null($log['participantLabel'])) ? '&ndash;' : $log['participantLabel'];
						echo '</td>';
						echo '<td>';
							echo (is_null($log['stepgroupLabel'])) ? '&ndash;' : $log['stepgroupLabel'];
						echo '</td>';
						echo '<td>';
							echo (is_null($log['stepgroupLoop'])) ? '&ndash;' : $log['stepgroupLoop'];
						echo '</td>';
						echo '<td>';
							echo (is_null($log['stepLabel'])) ? '&ndash;' : $log['stepLabel'];
						echo '</td>';
					echo '</table>';
				}
				if ($hasDetails)
				{
					echo '<pre>'. $this->escape($log['details']) . '</pre>';
				}
				if ($hasData)
				{
					$data = print_r( json_decode( $log['data'] ), true );
					echo 'Data<pre>'. $this->escape($data) . '</pre>';
				}
				echo '</div>';
			echo '</div>';
		}
	echo '</li>';
		
	$i++;
}
?>
</ul>
</div>

<?php
if ($maxPages > 1)
{
	echo '<div>Showing entries ' . $entriesFrom . ' - ' . $entriesTo . ' of ' . $this->count . ' entries</div>';
}
?>