<div class="table-responsive">
<table class="table table-striped table-hover">
<tr>
	<th>Session</th>
	<th>Procedural Context</th>
	<th>Person Context</th>
<?php
foreach($this->varNames as $varName)
{
	echo '<th>'.$this->escape($varName).'</th>';
}
?>
</tr>
<?php
foreach ( $this->variableRows as $variable )
{
	echo '<tr>';
		echo '<td>' . $variable['sessionId'] . '</td>';

		echo '<td>';
		if ($variable['stepgroupLabel'] != '')
		{
			echo $this->escape($variable['stepgroupLabel']);
		}
		if ($variable['stepgroupLabel'] != '')
		{
			echo ' - ' . $variable['stepgroupLoop'];
		}
		else
		{
			echo 'Everywhere';
		}
		echo '</td>';

		echo '<td>';
		if ($variable['groupLabel'] != '')
		{
			echo 'Group ' . $this->escape($variable['groupLabel']);
		}
		elseif ($variable['participantLabel'] != '')
		{
			echo 'Participant ' . $this->escape($variable['participantLabel']);
			if (isset($this->participantCodes))
			{
				echo ' / ' . $this->escape($this->participantCodes[$variable['participantLabel']]);
			}
		}
		else
		{
			echo 'Everyone';
		}
		echo '</td>';

		foreach($this->varNames as $varName)
		{
			echo '<td>';
			if (isset($variable[$varName]))
			{
				$value = $variable[$varName];
				if (is_array($value) || is_object($value))
				{
					echo '<pre>' . $this->escape(print_r($value, true)) . '</pre>';
				}
				else
				{
					echo $this->escape($value);
				}

			}
			echo '</td>';
		}

  echo '</tr>';
}

// add aggregate rows if supplied
if (isset($this->aggregateRows))
{
	foreach ($this->aggregateRows as $aggregateRow => $aggregateRowValues)
	{
		echo '<tr style="background: #dddddd;">';
		echo '<td colspan="3">' . $aggregateRow . '</td>';
		foreach($this->varNames as $varName)
		{
			echo '<td>' . $aggregateRowValues[$varName] . '</td>';
		}
		echo '</tr>';
	}
}
?>
</table>
</div>