<?php
echo $this->variableTabulateForm;
?>
<script type="text/javascript" >
jQuery('#filterNames').select2({
	width: '100%',
	placeholder: "Click or type to select",
	allowClear: true
});
jQuery('#filterStepgroupLabels').select2({
	width: '100%',
	placeholder: "Click or type to select",
	allowClear: true
});
jQuery('#addAggregateRows').select2({
	width: '100%',
	placeholder: "Click or type to select",
	allowClear: true
});
</script>